
// ------------------------------------------------------------------------------------------------
// Transformation: To Werewolf
// ------------------------------------------------------------------------------------------------
IF
    Global("PF_IS_WW","LOCALS",1)      // Opcode 309 just set this to 1
    !Global("PF_WW_MSG_STATE","LOCALS",1) // We haven't played the Werewolf message yet
THEN
    RESPONSE #100
        SetGlobal("PF_WW_MSG_STATE","LOCALS",1) // Mark that we are now in the WW state
        DisplayStringHead(Myself, 103728)       // "The beast awakens"
        AddSpecialAbility("PF#SPLFR")
END

// ------------------------------------------------------------------------------------------------
// Transformation: To Natural Form
// ------------------------------------------------------------------------------------------------
IF
    Global("PF_IS_WW","LOCALS",0)      // Opcode 309 just set this to 0
    !Global("PF_WW_MSG_STATE","LOCALS",0) // We haven't played the Natural message yet
THEN
    RESPONSE #100
        SetGlobal("PF_WW_MSG_STATE","LOCALS",0) // Mark that we are now in the Natural state
        DisplayStringHead(Myself, 103729)       // "The blood cools..."
        RemoveSpellRES("PF#SPLFR")
END