// ------------------------------------------------------------------------------------------------
// 1. Target Acquisition (Attack!)
// ------------------------------------------------------------------------------------------------
IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy(Myself),30)
END

// ------------------------------------------------------------------------------------------------
// 2. Help the Pack (If someone else is fighting)
// ------------------------------------------------------------------------------------------------
IF
    ActionListEmpty()
    !See([ENEMY])
    Heard([ANYONE],111)
    See(LastHeardBy(Myself))
THEN
    RESPONSE #100
        MoveToObject(LastSeenBy(Myself))
END

// ------------------------------------------------------------------------------------------------
// 3. Following the Master (Out of Combat)
// ------------------------------------------------------------------------------------------------
IF
    ActionListEmpty()
    CombatCounter(0)
    !See([ENEMY])
    !Range(LastSummonerOf(Myself),10)
THEN
    RESPONSE #100
        MoveToObject(LastSummonerOf(Myself))
END

// ------------------------------------------------------------------------------------------------
// 4. Idle/Wait
// ------------------------------------------------------------------------------------------------
// IF
//     ActionListEmpty()
//     !See([ENEMY])
//     Range(LastSummonerOf(Myself),10)
// THEN
//     RESPONSE #100
//         RandomWalk() // Makes them look more "alive" when standing around
// END