IF
	Heard([ANYONE],111)
THEN
	RESPONSE #100
		MoveToObject(NearestEnemyOf(Myself))
END

IF
    ActionListEmpty()                // 1. Only move if not already doing something
    CombatCounter(0)                 // 2. Only follow if not in combat
    !See([ENEMY])                    // 3. Don't wander off if enemies are nearby
    Allegiance(Myself,GOODCUTOFF)    // 4. Ensure it's still on your side
    !Range(LastSummonerOf(Myself),10) // 5. Don't step on the summoner's toes
THEN
    RESPONSE #100
        MoveToObject(LastSummonerOf(Myself))
END

// IF
// 	AttackedBy([GOODCUTOFF],DEFAULT)
// 	!Allegiance(Myself,ENEMY)
// THEN
// 	RESPONSE #100
// 		Enemy()
// END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	ActionListEmpty()
	AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		Attack(LastAttackerOf(Myself))
END

