
// ------------------------------------------------------------------------------------------------
// Transformation: To Werewolf
// ------------------------------------------------------------------------------------------------
IF
    Global("PF_IS_WW","LOCALS",1)      // Opcode 309 just set this to 1
    !Global("PF_WW_MSG_STATE","LOCALS",1) // We haven't played the Werewolf message yet
THEN
    RESPONSE #100
        SetGlobal("PF_WW_MSG_STATE","LOCALS",1) // Mark that we are now in the WW state
        DisplayStringHead(Myself, 103728)       // "The beast awakens"
        // AddSpecialAbility("PF#SPLFR")
        Wait(1)
        Continue()
END

IF
    Global("PF_IS_WW","LOCALS",1)      // Opcode 309 just set this to 1
    CheckStatGT(Myself, 0, 134) // Do I have at least 1 pick of the HLA?
    !Global("PF_MUF_MSG1","LOCALS",1) // We haven't played the muf message yet
THEN
    RESPONSE #100
        SetGlobal("PF_MUF_MSG1","LOCALS",1) // Mark that we are now in the WW state
        DisplayStringHead(Myself, 103733)       // Acknowledge ability existence
        Wait(1)
        Continue()
END

IF
    Global("PF_IS_WW","LOCALS",1)      // Opcode 309 just set this to 1
    CheckStatGT(Myself, 2, 134) // Do I have at least 3 pick of the HLA?
    !Global("PF_MUF_MSG2","LOCALS",1) // We haven't played the muf message yet
THEN
    RESPONSE #100
        SetGlobal("PF_MUF_MSG2","LOCALS",1) // Mark that we are now in the WW state
        Wait(1)
        DisplayString(Myself, 103734)       // Acknowledge ability existence
END

// ------------------------------------------------------------------------------------------------
// Transformation: To Natural Form
// ------------------------------------------------------------------------------------------------
IF
    Global("PF_IS_WW","LOCALS",0)      // Opcode 309 just set this to 0
    !Global("PF_WW_MSG_STATE","LOCALS",0) // We haven't played the Natural message yet
THEN
    RESPONSE #100
        SetGlobal("PF_WW_MSG_STATE","LOCALS",0) // Mark that we are now in the Natural state
        SetGlobal("PF_MUF_MSG1","LOCALS",0) // reset msg
        SetGlobal("PF_MUF_MSG2","LOCALS",0) // reset msg
        DisplayStringHead(Myself, 103729)       // "The blood cools..."
        RemoveSpellRES("PF#SPLFR")
END