IF
	Global("PF_DOHWL","LOCALS",1)
THEN
	RESPONSE #10
		SetGlobal("PF_DOHWL","LOCALS",0)
		Wait(1)
		PlaySound("PF#FWHL5")
	RESPONSE #10
		SetGlobal("PF_DOHWL","LOCALS",0)
		Wait(1)
		PlaySound("PF#FWHL6")
	RESPONSE #10
		SetGlobal("PF_DOHWL","LOCALS",0)
		Wait(1)
		PlaySound("PF#FWHL8")
	RESPONSE #10
		SetGlobal("PF_DOHWL","LOCALS",0)
		Wait(1)
		PlaySound("PF#FWHL1")
	RESPONSE #10
		SetGlobal("PF_DOHWL","LOCALS",0)
		Wait(1)
		PlaySound("PF#FWHL9")
	RESPONSE #10
		SetGlobal("PF_DOHWL","LOCALS",0)
		Wait(2)
		PlaySound("PF#FWHL5")
	RESPONSE #10
		SetGlobal("PF_DOHWL","LOCALS",0)
		Wait(2)
		PlaySound("PF#FWHL6")
	RESPONSE #10
		SetGlobal("PF_DOHWL","LOCALS",0)
		Wait(1)
		PlaySound("PF#FWHL8")
	RESPONSE #10
		SetGlobal("PF_DOHWL","LOCALS",0)
		Wait(1)
		PlaySound("PF#FWHL1")
	RESPONSE #10
		SetGlobal("PF_DOHWL","LOCALS",0)
		Wait(1)
		PlaySound("PF#FWHL9")
END

IF
	Global("PF_MyMasterSlot","LOCALS",0)
	Global("PF_CurrentSummoner","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("PF_MyMasterSlot","LOCALS",1)
END

IF
	Global("PF_MyMasterSlot","LOCALS",0)
	Global("PF_CurrentSummoner","GLOBAL",2)
THEN
	RESPONSE #100
		SetGlobal("PF_MyMasterSlot","LOCALS",2)
END

IF
	Global("PF_MyMasterSlot","LOCALS",0)
	Global("PF_CurrentSummoner","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("PF_MyMasterSlot","LOCALS",3)
END

IF
	Global("PF_MyMasterSlot","LOCALS",0)
	Global("PF_CurrentSummoner","GLOBAL",4)
THEN
	RESPONSE #100
		SetGlobal("PF_MyMasterSlot","LOCALS",4)
END

IF
	Global("PF_MyMasterSlot","LOCALS",0)
	Global("PF_CurrentSummoner","GLOBAL",5)
THEN
	RESPONSE #100
		SetGlobal("PF_MyMasterSlot","LOCALS",5)
END

IF
	Global("PF_MyMasterSlot","LOCALS",0)
	Global("PF_CurrentSummoner","GLOBAL",6)
THEN
	RESPONSE #100
		SetGlobal("PF_MyMasterSlot","LOCALS",6)
END

IF
	ActionListEmpty()
	!See([ENEMY])
	!See([PC.0.0.0.WOLF_SUMMONER])
	Global("PF_MyMasterSlot","LOCALS",1)
THEN
	RESPONSE #100
		FollowObjectFormation(Player1,2,2)
END

IF
	ActionListEmpty()
	!See([ENEMY])
	!See([PC.0.0.0.WOLF_SUMMONER])
	Global("PF_MyMasterSlot","LOCALS",2)
THEN
	RESPONSE #100
		FollowObjectFormation(Player2,2,2)
END

IF
	ActionListEmpty()
	!See([ENEMY])
	!See([PC.0.0.0.WOLF_SUMMONER])
	Global("PF_MyMasterSlot","LOCALS",3)
THEN
	RESPONSE #100
		FollowObjectFormation(Player3,2,2)
END

IF
	ActionListEmpty()
	!See([ENEMY])
	!See([PC.0.0.0.WOLF_SUMMONER])
	Global("PF_MyMasterSlot","LOCALS",4)
THEN
	RESPONSE #100
		FollowObjectFormation(Player4,2,2)
END

IF
	ActionListEmpty()
	!See([ENEMY])
	!See([PC.0.0.0.WOLF_SUMMONER])
	Global("PF_MyMasterSlot","LOCALS",5)
THEN
	RESPONSE #100
		FollowObjectFormation(Player5,2,2)
END

IF
	ActionListEmpty()
	!See([ENEMY])
	!See([PC.0.0.0.WOLF_SUMMONER])
	Global("PF_MyMasterSlot","LOCALS",6)
THEN
	RESPONSE #100
		FollowObjectFormation(Player6,2,2)
END

IF
	ActionListEmpty()
	!See([ENEMY])
	See([PC.0.0.0.WOLF_SUMMONER])
	!Range([PC.0.0.0.WOLF_SUMMONER],10)
THEN
	RESPONSE #100
		FollowObjectFormation([PC.0.0.0.WOLF_SUMMONER],2,2)
END

